blank_issues_enabled: true
contact_links:
  - name: 📚 Document
    url: https://github.com/JokerCrying/grpc-framework/blob/master/README.md
    about: Please check the document before asking a question.
  - name: 💬 Community
    url: https://github.com/JokerCrying/grpc-framework/discussions
    about: Welcome to ask questions and exchange ideas in the discussion community.
