# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x06simple\"L\n\rSimpleRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x03 \x01(\x05\"H\n\x0eSimpleResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2\x9b\x01\n\rSimpleService\x12\x44\n\x11GetSimpleResponse\x12\x15.simple.SimpleRequest\x1a\x16.simple.SimpleResponse\"\x00\x12\x44\n\x0fStreamResponses\x12\x15.simple.SimpleRequest\x1a\x16.simple.SimpleResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMPLEREQUEST']._serialized_start=25
  _globals['_SIMPLEREQUEST']._serialized_end=101
  _globals['_SIMPLERESPONSE']._serialized_start=103
  _globals['_SIMPLERESPONSE']._serialized_end=175
  _globals['_SIMPLESERVICE']._serialized_start=178
  _globals['_SIMPLESERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
